package com.example.ui.localization

import com.example.model.AppLanguage

data class LocalizedStrings(
    val appTitle: String,
    val appSubtitle: String,
    val settingsTitle: String,
    val accountProfile: String,
    val manageAccounts: String,
    val centProfile: String,
    val standardProfile: String,
    val specContract: String,
    val specMinLot: String,
    val specStep: String,
    val positionType: String,
    val buyLong: String,
    val sellShort: String,
    val entryPrice: String,
    val stopLossPrice: String,
    val takeProfitPrice: String,
    val riskSetting: String,
    val riskModePercentage: String,
    val riskModeAmount: String,
    val recommendedLotSize: String,
    val exactLotSize: String,
    val copyLot: String,
    val copiedMessage: String,
    val intendedRisk: String,
    val riskAmount: String = intendedRisk,
    val actualRisk: String,
    val stopLossDistance: String,
    val riskRewardRatio: String,
    val potentialProfit: String,
    val appearanceTheme: String,
    val themeDark: String,
    val themeLight: String,
    val themeSystem: String,
    val languageSelection: String,
    val quickPresetTitle: String,
    val quickPresetDesc: String,
    val loadPresetBtn: String,
    val currencyConverterTitle: String,
    val convertUSC: String,
    val convertUSD: String,
    val pipPrecisionTitle: String,
    val hapticFeedbackTitle: String,
    val clearInputs: String,
    val sampleTrade: String
)

object AppLocalization {

    fun get(language: AppLanguage): LocalizedStrings {
        return when (language) {
            AppLanguage.ENGLISH -> LocalizedStrings(
                appTitle = "GoldRisk",
                appSubtitle = "XAUUSD Risk & Lot Size Calculator",
                settingsTitle = "GoldRisk Settings & Preferences",
                accountProfile = "ACCOUNT PROFILE",
                manageAccounts = "Manage Accounts",
                centProfile = "Exness Standard Cent",
                standardProfile = "Exness Standard",
                specContract = "Contract Size",
                specMinLot = "Minimum Lot",
                specStep = "Lot Step",
                positionType = "Position Type",
                buyLong = "BUY / LONG",
                sellShort = "SELL / SHORT",
                entryPrice = "Entry Price",
                stopLossPrice = "Stop Loss Price",
                takeProfitPrice = "Take Profit Price (Optional)",
                riskSetting = "Risk Setting",
                riskModePercentage = "Percentage (%)",
                riskModeAmount = "Fixed Amount",
                recommendedLotSize = "RECOMMENDED LOT SIZE",
                exactLotSize = "Exact Lot Size",
                copyLot = "Copy Lot",
                copiedMessage = "Lot size copied to clipboard",
                intendedRisk = "Intended Risk",
                actualRisk = "Actual Risk at Recommended Lot",
                stopLossDistance = "Stop-Loss Distance",
                riskRewardRatio = "Risk-to-Reward Ratio",
                potentialProfit = "Potential Profit",
                appearanceTheme = "Theme Appearance",
                themeDark = "Dark Terminal",
                themeLight = "Light Mode",
                themeSystem = "System Default",
                languageSelection = "Language Selection",
                quickPresetTitle = "Exness Cent Scenario Preset",
                quickPresetDesc = "4144.888 Buy • 4130.341 SL • 4220.000 TP • 100 USC Risk",
                loadPresetBtn = "Apply Exness Cent Scenario",
                currencyConverterTitle = "Live USC ⇄ USD Converter",
                convertUSC = "USC (Cents)",
                convertUSD = "USD (Dollars)",
                pipPrecisionTitle = "Gold Pip Precision",
                hapticFeedbackTitle = "Haptic Vibration Feedback",
                clearInputs = "Clear",
                sampleTrade = "Sample"
            )
            AppLanguage.SPANISH -> LocalizedStrings(
                appTitle = "GoldRisk",
                appSubtitle = "Calculadora de Riesgo y Lote XAUUSD",
                settingsTitle = "Configuración de GoldRisk",
                accountProfile = "PERFIL DE CUENTA",
                manageAccounts = "Gestionar Cuentas",
                centProfile = "Exness Standard Cent",
                standardProfile = "Exness Standard",
                specContract = "Tamaño de Contrato",
                specMinLot = "Lote Mínimo",
                specStep = "Paso de Lote",
                positionType = "Tipo de Posición",
                buyLong = "COMPRA / LARGO",
                sellShort = "VENTA / CORTO",
                entryPrice = "Precio de Entrada",
                stopLossPrice = "Precio Stop Loss",
                takeProfitPrice = "Precio Take Profit (Opcional)",
                riskSetting = "Ajuste de Riesgo",
                riskModePercentage = "Porcentaje (%)",
                riskModeAmount = "Monto Fijo",
                recommendedLotSize = "LOTAJE RECOMENDADO",
                exactLotSize = "Lotaje Exacto",
                copyLot = "Copiar Lote",
                copiedMessage = "Tamaño de lote copiado",
                intendedRisk = "Riesgo Deseado",
                actualRisk = "Riesgo Real al Lote Recomendado",
                stopLossDistance = "Distancia de Stop-Loss",
                riskRewardRatio = "Ratio Riesgo / Beneficio",
                potentialProfit = "Beneficio Potencial",
                appearanceTheme = "Tema Visual",
                themeDark = "Modo Oscuro",
                themeLight = "Modo Claro",
                themeSystem = "Predeterminado del Sistema",
                languageSelection = "Selección de Idioma",
                quickPresetTitle = "Preset Cuenta Cent Exness",
                quickPresetDesc = "4144.888 Compra • 4130.341 SL • 4220.000 TP • 100 USC",
                loadPresetBtn = "Cargar Escenario Cent",
                currencyConverterTitle = "Conversor en Vivo USC ⇄ USD",
                convertUSC = "USC (Centavos)",
                convertUSD = "USD (Dólares)",
                pipPrecisionTitle = "Precisión de Decimales Oro",
                hapticFeedbackTitle = "Respuesta Háptica",
                clearInputs = "Limpiar",
                sampleTrade = "Ejemplo"
            )
            AppLanguage.FRENCH -> LocalizedStrings(
                appTitle = "GoldRisk",
                appSubtitle = "Calculateur de Risque et Lots XAUUSD",
                settingsTitle = "Paramètres de GoldRisk",
                accountProfile = "PROFIL DE COMPTE",
                manageAccounts = "Gérer les Comptes",
                centProfile = "Exness Standard Cent",
                standardProfile = "Exness Standard",
                specContract = "Taille du Contrat",
                specMinLot = "Lot Minimum",
                specStep = "Pas de Lot",
                positionType = "Type de Position",
                buyLong = "ACHAT / LONG",
                sellShort = "VENTE / COURT",
                entryPrice = "Prix d'Entrée",
                stopLossPrice = "Prix Stop Loss",
                takeProfitPrice = "Prix Take Profit (Optionnel)",
                riskSetting = "Paramètre de Risque",
                riskModePercentage = "Pourcentage (%)",
                riskModeAmount = "Montant Fixe",
                recommendedLotSize = "TAILLE DU LOT RECOMMANDÉE",
                exactLotSize = "Taille de Lot Exacte",
                copyLot = "Copier le Lot",
                copiedMessage = "Taille de lot copiée",
                intendedRisk = "Risque Prévu",
                actualRisk = "Risque Réel au Lot Recommandé",
                stopLossDistance = "Distance du Stop-Loss",
                riskRewardRatio = "Ratio Risque / Récompense",
                potentialProfit = "Profit Potentiel",
                appearanceTheme = "Apparence du Thème",
                themeDark = "Terminal Sombre",
                themeLight = "Mode Clair",
                themeSystem = "Système",
                languageSelection = "Choix de la Langue",
                quickPresetTitle = "Préréglage Compte Cent Exness",
                quickPresetDesc = "4144.888 Achat • 4130.341 SL • 4220.000 TP • 100 USC",
                loadPresetBtn = "Appliquer le Scénario Cent",
                currencyConverterTitle = "Convertisseur Direct USC ⇄ USD",
                convertUSC = "USC (Centimes)",
                convertUSD = "USD (Dollars)",
                pipPrecisionTitle = "Précision des Pips d'Or",
                hapticFeedbackTitle = "Retour Haptique",
                clearInputs = "Effacer",
                sampleTrade = "Exemple"
            )
            AppLanguage.GERMAN -> LocalizedStrings(
                appTitle = "GoldRisk",
                appSubtitle = "XAUUSD Risiko- & Lotgrößen-Rechner",
                settingsTitle = "GoldRisk Einstellungen",
                accountProfile = "KONTOPROFIL",
                manageAccounts = "Konten verwalten",
                centProfile = "Exness Standard Cent",
                standardProfile = "Exness Standard",
                specContract = "Kontraktgröße",
                specMinLot = "Mindest-Lot",
                specStep = "Lot-Schritt",
                positionType = "Positionstyp",
                buyLong = "KAUF / LONG",
                sellShort = "VERKAUF / SHORT",
                entryPrice = "Einstiegspreis",
                stopLossPrice = "Stop-Loss-Preis",
                takeProfitPrice = "Take-Profit-Preis (Optional)",
                riskSetting = "Risiko-Einstellung",
                riskModePercentage = "Prozentsatz (%)",
                riskModeAmount = "Fester Betrag",
                recommendedLotSize = "EMPFOHLENE LOTGRÖSSE",
                exactLotSize = "Exakte Lotgröße",
                copyLot = "Lot kopieren",
                copiedMessage = "Lotgröße in Zwischenablage kopiert",
                intendedRisk = "Beabsichtigtes Risiko",
                actualRisk = "Tatsächliches Risiko beim empf. Lot",
                stopLossDistance = "Stop-Loss-Abstand",
                riskRewardRatio = "Chance-Risiko-Verhältnis",
                potentialProfit = "Potenzieller Gewinn",
                appearanceTheme = "Design / Farbschema",
                themeDark = "Dunkles Terminal",
                themeLight = "Heller Modus",
                themeSystem = "Systemstandard",
                languageSelection = "Sprachauswahl",
                quickPresetTitle = "Exness Cent Szenario-Vorlage",
                quickPresetDesc = "4144.888 Kauf • 4130.341 SL • 4220.000 TP • 100 USC",
                loadPresetBtn = "Cent-Szenario laden",
                currencyConverterTitle = "Live USC ⇄ USD Währungsrechner",
                convertUSC = "USC (Cent)",
                convertUSD = "USD (Dollar)",
                pipPrecisionTitle = "Gold-Pip-Präzision",
                hapticFeedbackTitle = "Haptisches Feedback",
                clearInputs = "Zurücksetzen",
                sampleTrade = "Muster"
            )
            AppLanguage.INDONESIAN -> LocalizedStrings(
                appTitle = "GoldRisk",
                appSubtitle = "Kalkulator Risiko & Lot XAUUSD",
                settingsTitle = "Pengaturan & Preferensi GoldRisk",
                accountProfile = "PROFIL AKUN",
                manageAccounts = "Kelola Akun",
                centProfile = "Exness Standard Cent",
                standardProfile = "Exness Standard",
                specContract = "Ukuran Kontrak",
                specMinLot = "Lot Minimum",
                specStep = "Langkah Lot",
                positionType = "Jenis Posisi",
                buyLong = "BELI / LONG",
                sellShort = "JUAL / SHORT",
                entryPrice = "Harga Masuk (Entry)",
                stopLossPrice = "Harga Stop Loss",
                takeProfitPrice = "Harga Take Profit (Opsional)",
                riskSetting = "Pengaturan Risiko",
                riskModePercentage = "Persentase (%)",
                riskModeAmount = "Jumlah Tetap",
                recommendedLotSize = "UKURAN LOT DISARANKAN",
                exactLotSize = "Ukuran Lot Persis",
                copyLot = "Salin Lot",
                copiedMessage = "Ukuran lot disalin",
                intendedRisk = "Risiko yang Diinginkan",
                actualRisk = "Risiko Sebenarnya pada Lot Disarankan",
                stopLossDistance = "Jarak Stop-Loss",
                riskRewardRatio = "Rasio Risiko terhadap Hasil (R:R)",
                potentialProfit = "Potensi Keuntungan",
                appearanceTheme = "Tampilan Tema",
                themeDark = "Terminal Gelap",
                themeLight = "Mode Terang",
                themeSystem = "Bawaan Sistem",
                languageSelection = "Pilihan Bahasa",
                quickPresetTitle = "Preset Akun Cent Exness",
                quickPresetDesc = "4144.888 Beli • 4130.341 SL • 4220.000 TP • 100 USC",
                loadPresetBtn = "Terapkan Skenario Cent",
                currencyConverterTitle = "Konverter Langsung USC ⇄ USD",
                convertUSC = "USC (Sen)",
                convertUSD = "USD (Dolar)",
                pipPrecisionTitle = "Presisi Pip Emas",
                hapticFeedbackTitle = "Getaran Haptik",
                clearInputs = "Bersihkan",
                sampleTrade = "Contoh"
            )
            AppLanguage.ARABIC -> LocalizedStrings(
                appTitle = "GoldRisk",
                appSubtitle = "حاسبة مخاطر وحجم لوت الذهب XAUUSD",
                settingsTitle = "إعدادات وتفضيلات GoldRisk",
                accountProfile = "ملف الحساب",
                manageAccounts = "إدارة الحسابات",
                centProfile = "Exness Standard Cent",
                standardProfile = "Exness Standard",
                specContract = "حجم العقد",
                specMinLot = "أدنى لوت",
                specStep = "خطوة اللوت",
                positionType = "نوع الصفقة",
                buyLong = "شراء / BUY",
                sellShort = "بيع / SELL",
                entryPrice = "سعر الدخول",
                stopLossPrice = "سعر وقف الخسارة",
                takeProfitPrice = "سعر جني الأرباح (اختياري)",
                riskSetting = "إعداد المخاطرة",
                riskModePercentage = "نسبة مئوية (%)",
                riskModeAmount = "مبلغ محدد",
                recommendedLotSize = "حجم اللوت الموصى به",
                exactLotSize = "اللوت الدقيق",
                copyLot = "نسخ اللوت",
                copiedMessage = "تم نسخ حجم اللوت بنجاح",
                intendedRisk = "المخاطرة المحددة",
                actualRisk = "المخاطرة الفعلية عند اللوت الموصى به",
                stopLossDistance = "مسافة وقف الخسارة",
                riskRewardRatio = "نسبة العائد إلى المخاطرة",
                potentialProfit = "الربح المتوقع",
                appearanceTheme = "مظهر التطبيق",
                themeDark = "الوضع الداكن",
                themeLight = "الوضع الفاتح",
                themeSystem = "وضع النظام",
                languageSelection = "اختيار اللغة",
                quickPresetTitle = "إعداد مسبق لحساب السنت Exness",
                quickPresetDesc = "شراء 4144.888 • وقف 4130.341 • هدف 4220.000 • 100 USC",
                loadPresetBtn = "تحميل سيناريو السنت",
                currencyConverterTitle = "محول فوري USC ⇄ USD",
                convertUSC = "USC (سنت)",
                convertUSD = "USD (دولار)",
                pipPrecisionTitle = "دقة نقاط الذهب",
                hapticFeedbackTitle = "الاهتزاز اللمسي",
                clearInputs = "مسح",
                sampleTrade = "صفقة تجريبية"
            )
            AppLanguage.RUSSIAN -> LocalizedStrings(
                appTitle = "GoldRisk",
                appSubtitle = "Калькулятор Риска и Лота XAUUSD",
                settingsTitle = "Настройки GoldRisk",
                accountProfile = "ПРОФИЛЬ СЧЕТА",
                manageAccounts = "Управление счетами",
                centProfile = "Exness Standard Cent",
                standardProfile = "Exness Standard",
                specContract = "Размер контракта",
                specMinLot = "Мин. лот",
                specStep = "Шаг лота",
                positionType = "Тип позиции",
                buyLong = "ПОКУПКА / LONG",
                sellShort = "ПРОДАЖА / SHORT",
                entryPrice = "Цена входа",
                stopLossPrice = "Цена Stop Loss",
                takeProfitPrice = "Цена Take Profit (Опционально)",
                riskSetting = "Настройка риска",
                riskModePercentage = "Процент (%)",
                riskModeAmount = "Фиксированная сумма",
                recommendedLotSize = "РЕКОМЕНДОВАННЫЙ РАЗМЕР ЛОТА",
                exactLotSize = "Точный размер лота",
                copyLot = "Копировать лот",
                copiedMessage = "Размер лота скопирован",
                intendedRisk = "Планируемый риск",
                actualRisk = "Фактический риск при реком. лоте",
                stopLossDistance = "Дистанция Stop-Loss",
                riskRewardRatio = "Соотношение Риск/Прибыль",
                potentialProfit = "Потенциальная прибыль",
                appearanceTheme = "Оформление темы",
                themeDark = "Темный терминал",
                themeLight = "Светлая тема",
                themeSystem = "Как в системе",
                languageSelection = "Выбор языка",
                quickPresetTitle = "Пресет Exness Cent",
                quickPresetDesc = "4144.888 Покупка • 4130.341 SL • 4220.000 TP • 100 USC",
                loadPresetBtn = "Применить сценарий Cent",
                currencyConverterTitle = "Конвертер USC ⇄ USD",
                convertUSC = "USC (Центы)",
                convertUSD = "USD (Доллары)",
                pipPrecisionTitle = "Точность котировок золота",
                hapticFeedbackTitle = "Тактильный отклик",
                clearInputs = "Сброс",
                sampleTrade = "Пример"
            )
        }
    }
}
